import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const PAGES = ['Dashboard','Deal Command Centre','Deal Pipeline','Buy Box Rules','Acquisition Calculator','Scenario Comparison','Investors','Advisors / Brokers','Due Diligence','Follow-Ups','Documents','Settings / Data'];
const statuses = ['New lead','Watch','Request IM','NDA sent','Reviewing IM','Call broker','Financial review','DD candidate','Offer candidate','LOI submitted','Under DD','Negotiating','Passed','Dead','Acquired'];
const ddTemplate=['Last 3–4 years P&L','Balance sheets','Tax returns','EBITDA/add-back schedule','Monthly P&L latest year','Revenue by customer','Top 10 customers','Forward work/pipeline','Contracts/framework agreements','Staff structure','Owner duties','Asset schedule','Capex history','Debtors/creditors/WIP','GST/PAYE position','Compliance/licences','Health and safety','Employment agreements','Supplier concentration','Handover expectations','Vendor finance openness'];
const money=n=>`$${Number(n||0).toLocaleString()}`; const num=v=>Number(v||0);
const defaultScenario=(name='Base structure')=>({id:`s-${Date.now()}-${Math.random()}`,name,preferred:false,purchasePrice:0,cashAtSettlement:0,vendorFinance:0,seniorDebt:0,equityRequired:0,myContribution:0,investorEquity:0,investorCount:3,prefReturnPct:12,rjghOwnershipPct:40,investorOwnershipPct:60,debtServiceAnnual:0,vendorRepayAnnual:0,maintenanceCapex:0,growthReserve:0,mgmtFee:0,yearlyCashflowPreDebt:0});
const seed={selectedDealId:'d1',buyBox:{industries:['Traffic management','Civil support services','HVAC','Electrical','Pump services','Drainage','Plumbing','Commercial maintenance','Facilities maintenance','Fire/security/compliance','Equipment hire','Specialist trade services','Light industrial services','Other construction-adjacent services'],preferredRegions:['Manawatū','Whanganui','Horowhenua','Hawke’s Bay','Taranaki','Kapiti/Wellington','Taupō/Rotorua','Waikato','Lower/Central North Island'],considered:'Wider North Island where management depth and repeat revenue are strong.',revenueMin:1000000,revenueMax:5000000,earnMin:500000,earnMax:800000,evMin:500000,evMax:1800000,minQuality:'Repeat revenue + commercial demand',minEbitda:'$400k+',qualityRules:'Low owner dependence, customer <30%, forward work, understandable capex.',structure:'Debt + investor equity + vendor finance/deferred/earnout where needed. WC facility separate.',walkAway:'Weak financials, owner-only operations, high concentration, hidden capex, compliance/tax issues, no forward work.'},deals:[{id:'d1',name:'Central Traffic Services Ltd',industry:'Traffic management',location:'Manawatū',source:'Broker listing #NZ-8842',broker:'Harper Business Sales',askingPrice:895000,stock:'Excluded',revenue:2100000,ebitda:620000,workingOwnerProfit:680000,ownerReplacementSalary:140000,assetValue:380000,ownerRole:'GM + key relationships',staffDepth:'Moderate',recurringPct:65,customerConcentrationPct:28,forwardWork:'6 months contracted',capexRisk:'Medium',workingCapitalRisk:'Medium',fundingDifficulty:'Medium',sellerFinancePossible:'Yes',status:'Financial review',nextAction:'Request monthly P&L and top 10 customers',followUpDate:'2026-05-18',type:'Platform',notes:{broker:'',valuation:'',dd:'',structure:'',investor:'',negotiation:''},scoring:{ strategicFit:18, earningsQuality:16, fundability:17, managementDepth:11, recurringRevenue:8, assetCapex:7, growthPotential:4 },redFlags:{ ownerDependence:2, customerConcentration:1, earningsSpike:0, weakStaffDepth:1, poorRecords:0, highCapex:1, poorWorkingCapital:1, noForwardWork:0, complianceRisk:0, infoRefusal:0 },scenarios:[{...defaultScenario('Base structure'),preferred:true,purchasePrice:895000,cashAtSettlement:750000,vendorFinance:145000,seniorDebt:525000,equityRequired:225000,myContribution:50000,investorEquity:175000,investorCount:3,prefReturnPct:12,rjghOwnershipPct:40,investorOwnershipPct:60,debtServiceAnnual:98000,vendorRepayAnnual:15000,maintenanceCapex:45000,growthReserve:30000,mgmtFee:36000,yearlyCashflowPreDebt:310000}] }],ddItems:[],followUps:[],investors:[],advisors:[],documents:[]};

const calcScore=d=>Object.values(d.scoring||{}).reduce((a,b)=>a+num(b),0)-Object.values(d.redFlags||{}).reduce((a,b)=>a+num(b),0);
const prefScenario=d=>(d.scenarios||[]).find(s=>s.preferred)||(d.scenarios||[])[0]||defaultScenario();
const m=(d,s)=>{const managed=num(d.workingOwnerProfit)-num(d.ownerReplacementSalary);const prefGroup=num(s.investorEquity)*num(s.prefReturnPct)/100;const adj=num(s.yearlyCashflowPreDebt)-num(s.debtServiceAnnual)-num(s.vendorRepayAnnual)-num(s.maintenanceCapex)-num(s.growthReserve)-num(s.mgmtFee)-prefGroup;const invShare=Math.max(adj,0)*num(s.investorOwnershipPct)/100;return{managed,headline:num(d.askingPrice)/Math.max(num(d.ebitda),1),working:num(d.askingPrice)/Math.max(num(d.workingOwnerProfit),1),managedMult:num(d.askingPrice)/Math.max(managed,1),prefGroup,prefEach:prefGroup/Math.max(num(s.investorCount),1),invEach:num(s.investorEquity)/Math.max(num(s.investorCount),1),adj,invShare,rjShare:Math.max(adj,0)*num(s.rjghOwnershipPct)/100,coc:invShare/Math.max(num(s.investorEquity),1),dscr:num(s.yearlyCashflowPreDebt)/Math.max(num(s.debtServiceAnnual),1),payback:num(s.investorEquity)/Math.max(invShare,1)};};

function App(){const [data,setData]=useState(()=>JSON.parse(localStorage.getItem('crmData')||'null')||seed);const [page,setPage]=useState('Dashboard'); useEffect(()=>localStorage.setItem('crmData',JSON.stringify(data)),[data]);
const deals=data.deals||[];const deal=deals.find(x=>x.id===data.selectedDealId)||deals[0];const scenario=deal?prefScenario(deal):null;
const ddByDeal=useMemo(()=>{const map={};deals.forEach(d=>{const items=(data.ddItems||[]).filter(i=>i.dealId===d.id);map[d.id]={total:ddTemplate.length,received:items.filter(i=>i.status==='received').length,started:items.length>0};});return map;},[deals,data.ddItems]);
const dashboard=useMemo(()=>{const active=deals.filter(d=>!['Passed','Dead','Acquired'].includes(d.status));const top=[...deals].sort((a,b)=>calcScore(b)-calcScore(a)).slice(0,5);const byStatus=Object.fromEntries(statuses.map(s=>[s,deals.filter(d=>d.status===s).length]));const caps=active.reduce((a,d)=>{const s=prefScenario(d);a.debt+=num(s.seniorDebt);a.inv+=num(s.investorEquity);a.mine+=num(s.myContribution);a.vendor+=num(s.vendorFinance);a.cash+=num(s.cashAtSettlement);return a;},{debt:0,inv:0,mine:0,vendor:0,cash:0});const risks=active.map(d=>({d,s:prefScenario(d),mm:m(d,prefScenario(d))}));return{active:active.length,offers:byStatus['Offer candidate'],underDD:byStatus['Under DD'],byStatus,top,caps,avg:deals.length?deals.reduce((a,d)=>a+num(d.askingPrice)/Math.max(num(d.ebitda),1),0)/deals.length:0,best:top[0],nextFollow:[...deals].filter(d=>d.followUpDate).sort((a,b)=>a.followUpDate.localeCompare(b.followUpDate))[0],action:{overdue:deals.filter(d=>d.followUpDate && d.followUpDate<'2026-05-12').length,noAction:deals.filter(d=>!d.nextAction).length,red:deals.filter(d=>Object.values(d.redFlags||{}).reduce((a,b)=>a+b,0)>=5).length,waitingDD:deals.filter(d=>(ddByDeal[d.id]?.received||0)<5).length},risk:{lowDSCR:risks.filter(x=>x.mm.dscr<1.25).length,negCF:risks.filter(x=>x.mm.adj<0).length,highConc:active.filter(d=>num(d.customerConcentrationPct)>30).length,ownerDep:active.filter(d=>num(d.redFlags?.ownerDependence)>=2).length,weakStaff:active.filter(d=>(d.staffDepth||'').toLowerCase().includes('weak')).length,missingDD:active.filter(d=>(ddByDeal[d.id]?.received||0)<8).length}}},[deals,ddByDeal]);

const updDeal=(id,k,v)=>setData({...data,deals:deals.map(d=>d.id===id?{...d,[k]:v}:d)});
const addDeal=()=>{const nd={id:`d-${Date.now()}`,name:'New Deal',industry:'',location:'',source:'',broker:'',askingPrice:0,stock:'',revenue:0,ebitda:0,workingOwnerProfit:0,ownerReplacementSalary:0,assetValue:0,ownerRole:'',staffDepth:'',recurringPct:0,customerConcentrationPct:0,forwardWork:'',capexRisk:'',workingCapitalRisk:'',fundingDifficulty:'',sellerFinancePossible:'',status:'New lead',nextAction:'',followUpDate:'',type:'Bolt-on',notes:{broker:'',valuation:'',dd:'',structure:'',investor:'',negotiation:''},scoring:{ strategicFit:0, earningsQuality:0, fundability:0, managementDepth:0, recurringRevenue:0, assetCapex:0, growthPotential:0 },redFlags:{ ownerDependence:0, customerConcentration:0, earningsSpike:0, weakStaffDepth:0, poorRecords:0, highCapex:0, poorWorkingCapital:0, noForwardWork:0, complianceRisk:0, infoRefusal:0 },scenarios:[defaultScenario()]};setData({...data,deals:[...deals,nd],selectedDealId:nd.id})}
const exportJson=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='rjgh-crm.json';a.click()};
const importJson=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setData(JSON.parse(String(r.result)))}catch{alert('Invalid JSON')}};r.readAsText(f)};

return <div className='shell'><aside className='sidebar'><h2>RJGH CRM</h2><p className='muted'>Saved locally</p>{PAGES.map(p=><button key={p} className={page===p?'nav active':'nav'} onClick={()=>setPage(p)}>{p}</button>)}</aside><main className='main'><header className='top'><div><h1>{page==='Dashboard'?'RJGH Acquisition Dashboard':page}</h1><p className='muted'>{page==='Dashboard'?'Pipeline, funding, follow-ups, and deal quality overview':'Decision-oriented acquisition workflow'}</p></div><div>{deals.length>0&&<select value={deal?.id||''} onChange={e=>setData({...data,selectedDealId:e.target.value})}>{deals.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>}</div></header>
{deals.length===0&&page!=='Settings / Data'?<Empty text='No deals yet. Add your first deal in Deal Pipeline.'/>:null}
{page==='Dashboard'&&<Dashboard dashboard={dashboard} deals={deals}/>} 
{page==='Deal Command Centre'&&<Command deal={deal} dd={ddByDeal[deal?.id]} />} 
{page==='Deal Pipeline'&&<Pipeline deals={deals} updDeal={updDeal} addDeal={addDeal} setData={setData} data={data}/>} 
{page==='Buy Box Rules'&&<BuyBox data={data} setData={setData}/>} 
{page==='Acquisition Calculator'&&deal&&<Calculator deal={deal} data={data} setData={setData}/>} 
{page==='Scenario Comparison'&&deal&&<Scenarios deal={deal} data={data} setData={setData}/>} 
{page==='Due Diligence'&&deal&&<DD deal={deal} data={data} setData={setData}/>} 
{['Investors','Advisors / Brokers','Follow-Ups','Documents'].includes(page)&&<section className='card'><h3>{page}</h3><p className='muted'>Simple module placeholder (MVP retained).</p></section>}
{page==='Settings / Data'&&<section className='card'><h3>Settings / Data</h3><p>Local storage status: <b>Active</b></p><p>Selected deal: <b>{deal?.name||'None'}</b></p><p>Deals saved: <b>{deals.length}</b></p><p className='muted'>Data is stored in browser localStorage key <code>crmData</code>.</p><div className='row'><button onClick={exportJson}>Export JSON</button><label className='file'>Import JSON<input type='file' accept='application/json' onChange={importJson}/></label><button className='danger' onClick={()=>setData(seed)}>Reset Demo Data</button></div></section>}
</main></div>}

const Empty=({text})=><section className='card'><p className='muted'>{text}</p></section>;
const badge=(t,c='')=><span className={`badge ${c}`}>{t}</span>;
function Dashboard({dashboard,deals}){return <><div className='cards'>{[['Total deals reviewed',deals.length],['Active deals',dashboard.active],['Offer candidates',dashboard.offers],['Under DD',dashboard.underDD],['Total equity required',money(dashboard.caps.inv+dashboard.caps.mine)],['Investor capital required',money(dashboard.caps.inv)],['My capital required',money(dashboard.caps.mine)],['Senior debt proposed',money(dashboard.caps.debt)],['Vendor finance proposed',money(dashboard.caps.vendor)],['Average EBITDA multiple',dashboard.avg.toFixed(2)+'x'],['Best deal by score',dashboard.best?.name||'-'],['Next follow-up due',dashboard.nextFollow?.followUpDate||'-']].map(([k,v])=><div className='metric' key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>
<div className='grid2'><section className='card'><h3>Pipeline Overview</h3>{Object.entries(dashboard.byStatus).filter(([,v])=>v>0).map(([k,v])=><div key={k} className='line'>{badge(k)} <b>{v}</b></div>)}</section>
<section className='card'><h3>Capital Requirements</h3><p>Debt {money(dashboard.caps.debt)} | Investor {money(dashboard.caps.inv)} | RJGH {money(dashboard.caps.mine)}</p><p>Vendor {money(dashboard.caps.vendor)} | Cash at settlement {money(dashboard.caps.cash)}</p></section>
<section className='card'><h3>Best Opportunities</h3>{dashboard.top.map(d=><div key={d.id} className='line'>{d.name} <b>{calcScore(d)}</b></div>)}</section>
<section className='card'><h3>Action Centre</h3><p>Overdue: {dashboard.action.overdue} · No next action: {dashboard.action.noAction} · Waiting DD: {dashboard.action.waitingDD} · Red-flagged: {dashboard.action.red}</p></section>
<section className='card'><h3>Risk Snapshot</h3><p>DSCR &lt;1.25x: {dashboard.risk.lowDSCR} · Negative cashflow: {dashboard.risk.negCF}</p><p>Concentration&gt;30%: {dashboard.risk.highConc} · Owner dependence: {dashboard.risk.ownerDep} · Missing DD: {dashboard.risk.missingDD}</p></section></div></>}
function Command({deal,dd}){if(!deal) return <Empty text='Select a deal to open command centre.'/>; const sc=prefScenario(deal); const mm=m(deal,sc); const verdict=calcScore(deal)>75&&mm.dscr>1.25&&mm.adj>0?'Strong platform candidate':mm.dscr>1.1?'Fundable, needs structure':mm.adj<0?'High risk, structure required':deal.status==='Watch'?'Watch only':'Pass'; const risks=[]; if(num(deal.redFlags.ownerDependence)>1) risks.push('Owner dependence'); if(num(deal.customerConcentrationPct)>30) risks.push('Customer concentration'); if(mm.dscr<1.25) risks.push('DSCR below 1.25x'); if(mm.adj<0) risks.push('Negative adjusted cashflow'); if(mm.coc*100<num(sc.prefReturnPct)) risks.push('Low investor return'); if((deal.capexRisk||'').toLowerCase().includes('high')) risks.push('High capex'); if((deal.staffDepth||'').toLowerCase().includes('weak')) risks.push('Weak staff depth'); if((dd?.received||0)<8) risks.push('Missing DD'); if(!deal.forwardWork) risks.push('No forward work'); return <div className='grid2'><section className='card'><h3>{deal.name}</h3><p>{deal.industry} · {deal.location} · {badge(deal.status)}</p><p>Type: {deal.type} · Broker: {deal.broker}</p><p>Next: {deal.nextAction||'Not set'} ({deal.followUpDate||'No date'})</p><p>Score: <b>{calcScore(deal)}</b> · Verdict: <b>{verdict}</b></p></section><section className='card'><h3>Snapshots</h3><p>Headline multiple {mm.headline.toFixed(2)}x · Managed EBITDA {money(mm.managed)} · DSCR {mm.dscr.toFixed(2)}x</p><p>Equity {money(sc.equityRequired)} · Investor {money(sc.investorEquity)} · Debt {money(sc.seniorDebt)}</p><p>DD Progress: {dd?.received||0}/{dd?.total||ddTemplate.length}</p></section><section className='card'><h3>Risk Badges</h3><div className='row'>{risks.length?risks.map(r=>badge(r,'risk')):'No major risk badges'}</div></section><section className='card'><h3>Investor readiness</h3><div className='line'>{badge(mm.dscr>=1.25?'DSCR acceptable':'DSCR needs work',mm.dscr>=1.25?'ok':'risk')}</div><div className='line'>{badge(mm.coc*100>=sc.prefReturnPct?'Investor return acceptable':'Investor return needs work',mm.coc*100>=sc.prefReturnPct?'ok':'risk')}</div></section><section className='card'><h3>Offer guidance</h3><p>Indicated value: {money(mm.managed*2.8)}</p><p>Recommended offer: {money(mm.managed*2.5)}</p><p>Walk-away max: {money(mm.managed*3)}</p><p className='muted'>Structure note: Use more vendor finance/earnout if DSCR or concentration risk weakens.</p></section><section className='card'><h3>Broker question helper</h3><ul>{(!deal.customerConcentrationPct)&&<li>Provide top 10 customers and revenue split.</li>}{(!deal.capexRisk)&&<li>Provide asset schedule and capex history.</li>}{(!deal.ebitda)&&<li>Provide financials and add-back schedule.</li>}{(!deal.staffDepth)&&<li>Provide org chart and key staff duties.</li>}{(!deal.forwardWork)&&<li>Provide pipeline and contracted forward work evidence.</li>}</ul></section></div>}
function Pipeline({deals,updDeal,addDeal,setData,data}){return <section className='card'><div className='row spread'><h3>Deal Pipeline</h3><button onClick={addDeal}>+ Add Deal</button></div><div className='tableWrap'><table><thead><tr><th>Select</th><th>Name</th><th>Industry</th><th>Location</th><th>Status</th><th>Type</th><th>Price</th><th>Revenue</th><th>EBITDA</th><th>WOP</th><th>Owner Salary</th><th>Managed EBITDA</th><th>Concentration %</th><th>Capex</th><th>Next action</th><th>Follow-up</th></tr></thead><tbody>{deals.map(d=><tr key={d.id}><td><input type='radio' checked={data.selectedDealId===d.id} onChange={()=>setData({...data,selectedDealId:d.id})}/></td><td><input value={d.name} onChange={e=>updDeal(d.id,'name',e.target.value)}/></td><td><input value={d.industry||''} onChange={e=>updDeal(d.id,'industry',e.target.value)}/></td><td><input value={d.location||''} onChange={e=>updDeal(d.id,'location',e.target.value)}/></td><td><select value={d.status} onChange={e=>updDeal(d.id,'status',e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><select value={d.type||'Bolt-on'} onChange={e=>updDeal(d.id,'type',e.target.value)}><option>Platform</option><option>Bolt-on</option></select></td><td><input type='number' value={d.askingPrice||0} onChange={e=>updDeal(d.id,'askingPrice',num(e.target.value))}/></td><td><input type='number' value={d.revenue||0} onChange={e=>updDeal(d.id,'revenue',num(e.target.value))}/></td><td><input type='number' value={d.ebitda||0} onChange={e=>updDeal(d.id,'ebitda',num(e.target.value))}/></td><td><input type='number' value={d.workingOwnerProfit||0} onChange={e=>updDeal(d.id,'workingOwnerProfit',num(e.target.value))}/></td><td><input type='number' value={d.ownerReplacementSalary||0} onChange={e=>updDeal(d.id,'ownerReplacementSalary',num(e.target.value))}/></td><td>{money(num(d.workingOwnerProfit)-num(d.ownerReplacementSalary))}</td><td><input type='number' value={d.customerConcentrationPct||0} onChange={e=>updDeal(d.id,'customerConcentrationPct',num(e.target.value))}/></td><td><input value={d.capexRisk||''} onChange={e=>updDeal(d.id,'capexRisk',e.target.value)}/></td><td><input value={d.nextAction||''} onChange={e=>updDeal(d.id,'nextAction',e.target.value)}/></td><td><input type='date' value={d.followUpDate||''} onChange={e=>updDeal(d.id,'followUpDate',e.target.value)}/></td></tr>)}</tbody></table></div></section>}
function BuyBox({data,setData}){const b=data.buyBox;const up=(k,v)=>setData({...data,buyBox:{...b,[k]:v}});return <div className='grid2'><section className='card'><h3>Target Industries</h3><div className='chips'>{(b.industries||[]).map((x,i)=><span key={i} className='chip'>{x}</span>)}</div><textarea value={(b.industries||[]).join('\n')} onChange={e=>up('industries',e.target.value.split('\n').filter(Boolean))}/></section><section className='card'><h3>Target Geography</h3><textarea value={(b.preferredRegions||[]).join('\n')} onChange={e=>up('preferredRegions',e.target.value.split('\n').filter(Boolean))}/><textarea value={b.considered||''} onChange={e=>up('considered',e.target.value)} /></section><section className='card'><h3>Financial Buy Box</h3><div className='grid'>{['revenueMin','revenueMax','earnMin','earnMax','evMin','evMax'].map(k=><label key={k}>{k}<input type='number' value={b[k]||0} onChange={e=>up(k,num(e.target.value))}/></label>)}</div></section><section className='card'><h3>Deal Quality Rules</h3><textarea value={b.qualityRules||''} onChange={e=>up('qualityRules',e.target.value)} /></section><section className='card'><h3>Preferred Deal Structure</h3><textarea value={b.structure||''} onChange={e=>up('structure',e.target.value)} /></section><section className='card warn'><h3>Walk-Away Rules</h3><textarea value={b.walkAway||''} onChange={e=>up('walkAway',e.target.value)} /></section></div>}
function Calculator({deal,data,setData}){const sc=prefScenario(deal);const mm=m(deal,sc);const upd=(k,v)=>{const ds=data.deals.map(d=>d.id!==deal.id?d:{...d,scenarios:d.scenarios.map(s=>s.id===sc.id?{...s,[k]:num(v)}:s)});setData({...data,deals:ds})};const updDeal=(k,v)=>setData({...data,deals:data.deals.map(d=>d.id===deal.id?{...d,[k]:num(v)}:d)});return <div className='grid2'><section className='card'><h3>Deal Earnings</h3>{['revenue','ebitda','workingOwnerProfit','ownerReplacementSalary'].map(k=><label key={k}>{k}<input type='number' value={deal[k]||0} onChange={e=>updDeal(k,e.target.value)}/></label>)}</section><section className='card'><h3>Purchase Structure</h3>{['purchasePrice','cashAtSettlement','vendorFinance','seniorDebt','equityRequired','myContribution','investorEquity'].map(k=><label key={k}>{k}<input type='number' value={sc[k]||0} onChange={e=>upd(k,e.target.value)}/></label>)}</section><section className='card'><h3>Investor Structure</h3>{['investorCount','prefReturnPct','rjghOwnershipPct','investorOwnershipPct'].map(k=><label key={k}>{k}<input type='number' value={sc[k]||0} onChange={e=>upd(k,e.target.value)}/></label>)}</section><section className='card'><h3>Cashflow Assumptions</h3>{['debtServiceAnnual','vendorRepayAnnual','maintenanceCapex','growthReserve','mgmtFee','yearlyCashflowPreDebt'].map(k=><label key={k}>{k}<input type='number' value={sc[k]||0} onChange={e=>upd(k,e.target.value)}/></label>)}</section><section className='card'><h3>Outputs / Returns</h3><p>Headline multiple {mm.headline.toFixed(2)}x · Working-owner {mm.working.toFixed(2)}x · Managed {mm.managedMult.toFixed(2)}x</p><p>Investor each {money(mm.invEach)} · Each ownership {(num(sc.investorOwnershipPct)/Math.max(num(sc.investorCount),1)).toFixed(1)}%</p><p>Pref group {money(mm.prefGroup)} · Pref each {money(mm.prefEach)}</p><p className={mm.adj<0?'riskText':''}>Adjusted cashflow {money(mm.adj)}</p><p>Investor share {money(mm.invShare)} · RJGH share {money(mm.rjShare)}</p><p className={mm.dscr<1.25?'riskText':''}>DSCR {mm.dscr.toFixed(2)}x</p><p className={mm.payback>5?'riskText':''}>Payback {mm.payback.toFixed(1)} years</p><p className={mm.coc*100<sc.prefReturnPct?'riskText':''}>Cash-on-cash {(mm.coc*100).toFixed(1)}%</p></section></div>}
function Scenarios({deal,data,setData}){const setSc=(arr)=>setData({...data,deals:data.deals.map(d=>d.id===deal.id?{...d,scenarios:arr}:d)});const arr=deal.scenarios||[]; if(!arr.length) return <Empty text='No scenarios. Add one to compare structures.'/>; return <section className='card'><div className='row'><button onClick={()=>setSc([...arr,defaultScenario('Custom')])}>Add scenario</button><button onClick={()=>setSc([...arr,{...arr[0],id:`s-${Date.now()}`,name:`${arr[0].name} copy`,preferred:false}])}>Duplicate scenario</button><button onClick={()=>arr.length>1&&setSc(arr.slice(0,-1))}>Delete last</button></div><div className='tableWrap'><table><thead><tr><th>Preferred</th><th>Name</th><th>Debt</th><th>Vendor</th><th>Equity</th><th>Investor each</th><th>Pref</th><th>Adj cashflow</th><th>DSCR</th><th>CoC</th><th>Payback</th></tr></thead><tbody>{arr.map(s=>{const mm=m(deal,s);return <tr key={s.id}><td><input type='radio' checked={!!s.preferred} onChange={()=>setSc(arr.map(x=>({...x,preferred:x.id===s.id})))}/></td><td><input value={s.name} onChange={e=>setSc(arr.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/></td><td>{money(s.seniorDebt)}</td><td>{money(s.vendorFinance)}</td><td>{money(s.equityRequired)}</td><td>{money(mm.invEach)}</td><td>{money(mm.prefGroup)}</td><td>{money(mm.adj)}</td><td>{mm.dscr.toFixed(2)}x</td><td>{(mm.coc*100).toFixed(1)}%</td><td>{mm.payback.toFixed(1)}</td></tr>})}</tbody></table></div></section>}
function DD({deal,data,setData}){const items=ddTemplate.map(n=>{const found=(data.ddItems||[]).find(i=>i.dealId===deal.id&&i.item===n);return found||{id:`${deal.id}-${n}`,dealId:deal.id,item:n,status:'missing'};});const update=(it,status)=>{const rest=(data.ddItems||[]).filter(x=>!(x.dealId===it.dealId&&x.item===it.item));setData({...data,ddItems:[...rest,{...it,status}]})};const rec=items.filter(x=>x.status==='received').length;return <section className='card'><h3>Due Diligence ({rec}/{items.length} received · {Math.round(rec/items.length*100)}%)</h3><table><thead><tr><th>Item</th><th>Status</th></tr></thead><tbody>{items.map(it=><tr key={it.id}><td>{it.item}</td><td><select value={it.status} onChange={e=>update(it,e.target.value)}><option value='missing'>missing</option><option value='requested'>requested</option><option value='received'>received</option></select></td></tr>)}</tbody></table></section>}

createRoot(document.getElementById('root')).render(<App/>);
